### ISSUE TITLE
1_fizz_buzz Comments

### ISSUE THREAD

**Issue by paaaco** [ark-prl/adish-git-repository#1]
https://github.com/ark-prl/adish-git-repository/blob/4fec813e13804b2dfa7b9709a2cd34db896472bb/Internship/1_fizz_buzz.rb#L10-L21

* Try to redo this logic using [the `.each` method](https://apidock.com/ruby/Range/each). `while` (and `for`) loops aren't usually used in Ruby code because it is a lot easier to use iterator methods over a range/array (no need to keep track of an `index` variable).
* A refactor exercise: let's say sometime in the future we want to change the "rules" of the exercise (instead of "multiple of 3" = "Fizz", it will be "multiple of 7" = "Hoge"). Refactor this code so that if ever the rules do change, a developer will only have to change some variables in the code.
   * **note**: assume that the underlying logic will always be the same:
      - if multiple of _a_, display _b_
      - if multiple of _c_, display _d_
      - if multiple of _a_ and _c_, display _b_ _d_

**Comment by ark-prl** [comment]
Implemented the `.each` method and the _refactor exercise_.
