### ISSUE TITLE
2_hashtags comments

### ISSUE THREAD

**Issue by paaaco** [ark-prl/adish-git-repository#2]
https://github.com/ark-prl/adish-git-repository/blob/a8de106810033a291614f21b3e2fcb15bf915b5d/Internship/2_hashtags.rb#L28-L31

Similar to Issue #1 , try to use `.each` here instead of a `while` loop.

**Comment by ark-prl** [comment]
Implemented the `.each` method.

**Comment by ark-prl** [comment]
Closing this issue.
