### ISSUE TITLE
3_max_product_pair comments

### ISSUE THREAD

**Issue by paaaco** [ark-prl/adish-git-repository#3]
https://github.com/ark-prl/adish-git-repository/blob/174c286bd1b263660cdaa0126b99a136bfb50c97/Internship/3_max_product_pair.rb#L22-L29

I guess your logic here is: 
* get the values of a•d, a•b, c•d
* get the maximum value from those three

This can be heavily simplified using the `Array#max` method. Ex:

```
$ [1, 3, 2].max
=> 3
```

**Comment by ark-prl** [comment]
Implemented the `.max` method to simplify code.
